name: elearning_app
description: "An e-learning platform for online courses, video lectures, quizzes, and progress tracking."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

# Dart SDK constraints
environment:
  sdk: '>=3.0.0 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.0 # Updated to the latest stable version
  http: ^1.2.0 # Updated to the latest stable version
  provider: ^6.1.0 # Updated to the latest stable version
  shared_preferences: ^2.2.2 # Updated to the latest stable version
  cupertino_icons: ^1.0.8 # For iOS-style icons
  firebase_core: ^2.24.0 # Updated to the latest stable version
  firebase_auth: ^4.11.0 # Updated to the latest stable version
  cloud_firestore: ^4.16.0 # Updated to the latest stable version

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # For linting and code quality

# Flutter-specific configuration
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/ # Folder containing images
    # - assets/fonts/OpenSans-Regular.ttf (removed because the file doesn't exist)
    # - assets/fonts/OpenSans-Bold.ttf
    # - assets/fonts/OpenSans-Italic.ttf (removed because the file doesn't exist)

  # Custom fonts
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic