name: elearning_app
description: "An e-learning platform for online courses, video lectures, quizzes, and progress tracking."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

# Dart SDK constraints
environment:
  sdk: '>=3.0.0 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.0 # Updated to the latest stable version
  http: ^1.2.0 # Updated to the latest stable version
  provider: ^6.1.0 # Updated to the latest stable version
  shared_preferences: ^2.2.2 # Updated to the latest stable version
  cupertino_icons: ^1.0.8 # For iOS-style icons
  firebase_core: ^2.24.0 # Updated to the latest stable version
  firebase_auth: ^4.11.0 # Updated to the latest stable version
  cloud_firestore: ^4.16.0 # Updated to the latest stable version
  flutter_secure_storage: ^9.2.4 # Corrected version constraint for compatibility
  url_launcher: ^6.3.1

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # For linting and code quality
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0 # Added for custom launcher icons

# Flutter-specific configuration
flutter:
  uses-material-design: true