// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjewuQyObi0IHbLDbc2oAXCIzAplCp3_0',
    appId: '1:339450379790:web:30d7c0a188fee82245865f',
    messagingSenderId: '339450379790',
    projectId: 'nexareality',
    authDomain: 'nexareality.firebaseapp.com',
    storageBucket: 'nexareality.firebasestorage.app',
    measurementId: 'G-Q1GRRM3MXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvKSpV8I0Qp3P85zbnSxJVBTg6IQXKhxg',
    appId: '1:339450379790:android:3049d825af3dd0ba45865f',
    messagingSenderId: '339450379790',
    projectId: 'nexareality',
    storageBucket: 'nexareality.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_mNXVfrQLMxWO8G4shylwvPlpT4DZsRU',
    appId: '1:339450379790:ios:f2fc883e81c45ef045865f',
    messagingSenderId: '339450379790',
    projectId: 'nexareality',
    storageBucket: 'nexareality.firebasestorage.app',
    iosBundleId: 'com.example.elearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_mNXVfrQLMxWO8G4shylwvPlpT4DZsRU',
    appId: '1:339450379790:ios:f2fc883e81c45ef045865f',
    messagingSenderId: '339450379790',
    projectId: 'nexareality',
    storageBucket: 'nexareality.firebasestorage.app',
    iosBundleId: 'com.example.elearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjewuQyObi0IHbLDbc2oAXCIzAplCp3_0',
    appId: '1:339450379790:web:d50a2ef4ed52312845865f',
    messagingSenderId: '339450379790',
    projectId: 'nexareality',
    authDomain: 'nexareality.firebaseapp.com',
    storageBucket: 'nexareality.firebasestorage.app',
    measurementId: 'G-1NX24J5BFE',
  );
}
